### ISSUE TITLE
ids.txt

### ISSUE THREAD

**Issue by Voltzy** [summer/steam-autoclaimer#1]
Keeps telling my to create ids.txt in the location of the script but its already there.

**Comment by summer** [comment]
Are you running the .py script by double clicking on it? Navigate to the directory via command prompt and then run it with `py claim.py` ([example](https://i.imgur.com/2dvVYJ1.png))

**Comment by Voltzy** [comment]
> Are you running the .py script by double clicking on it? Navigate to the directory via command prompt and then run it with `py claim.py` ([example](https://i.imgur.com/2dvVYJ1.png))

Yeah I have tried double clicking on the script, launching it through cmd and what-not.
When I double click and go through the process, after logging in it flashes the message for a split second then closes entirely.
When I run through cmd it shows the "Create ids.txt" line (its obviously different than exactly that) but does exit the script and goes back to the default cmd the line below.

**Comment by Voltzy** [comment]
edit: Fixed issue. Little corruption happened during download.
So far so good now. at the "converting" step

**Comment by Voltzy** [comment]
r
